name: Terraform HCL validation (PRs only)

on:
  pull_request:
    paths: ["**.tf"]

jobs:
  terraform-module-k3s:
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.lint.yaml@374b560c4a555ce0e76665d60985ab3be07e5b1e
    with:
      terraform_workdir: fixtures/terraform/project-01

  examples_hcloud-k3s:
    needs: [terraform-module-k3s]
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.lint.yaml@374b560c4a555ce0e76665d60985ab3be07e5b1e
    with:
      terraform_workdir: examples/hcloud-k3s

  examples_civo-k3s:
    needs: [terraform-module-k3s]
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.lint.yaml@374b560c4a555ce0e76665d60985ab3be07e5b1e
    with:
      terraform_workdir: examples/civo-k3s
