name: Terraform - PR validation

on:
  pull_request:
    paths: ["**.tf"]

jobs:
  lint:
    name: Terraform - PR lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # renovate: tag=v1.3.2
      - run: terraform init -backend=false
      - run: terraform fmt -check -recursive -diff -no-color

  validate:
    name: Terraform - PR validate
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: ["examples/hcloud-k3s", "examples/civo-k3s"]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # renovate: tag=v1.3.2
      - run: terraform init -backend=false
        working-directory: ${{ matrix.workdir }}
      - run: terraform validate
        working-directory: ${{ matrix.workdir }}
